eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://192.168.3.208:8761/eureka/
      
server:
  port: 8765
feign: 
  hystrix:
    enabled: true
spring:
  application:
    name: eshop-datasync-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.3.205:3306/eshop
    username: root
    password: root
  rabbitmq:
    host: 192.168.3.205
    port: 5672  
    username: rabbitadmin  
    password: 123456
   
    
   